apiVersion: v1
kind: Template
metadata:
  name: testcase-01
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "testcase-01"
    namespace: ${NAMESPACE}
  spec:
    source:
      git:
        uri: ${GIT_REPO}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: testcase-01/Jenkinsfile
        env:
          - name: SECRET_NAME
            value: ${SECRET_NAME}
          - name: NAMESPACE
            value: ${NAMESPACE}
          - name: TARGET_INSTANCE
            value: ${TARGET_INSTANCE}
parameters:
- name: SECRET_NAME
  value: 3scale-toolbox
- name: NAMESPACE
  value: api-lifecycle
- name: TARGET_INSTANCE
  value: nmasse-redhat
- name: GIT_REPO
  value: https://github.com/nmasse-itix/API-Lifecycle-Mockup.git
